const actionTypes = {
  ZOOM_CHANGE: "ZOOM_CHANGE",
  FIRST_LATLNG: "FIRST_LATLNG",
  SECOND_LATLNG: "SECOND_LATLNG",
  RESET: "RESET",
  CENTER: "CENTER",
  CREATE_LINE_MAPBOX: "CREATE_LINE_MAPBOX",
  CREATE_LINE_OPENLAYER: "CREATE_LINE_OPENLAYER",
};

export default actionTypes;
